server:
  port: 7091
  undo:
    logSaveDays: 7
    # undo清理线程间隔时间 默认86400000，单位毫秒
    logDeletePeriod: 86400000
    # 二阶段提交重试超时时长 单位ms,s,m,h,d,对应毫秒,秒,分,小时,天,默认毫秒。默认值-1表示无限重试
    # 公式: timeout>=now-globalTransactionBeginTime,true表示超时则不再重试
    # 注: 达到超时时间后将不会做任何重试,有数据不一致风险,除非业务自行可校准数据,否者慎用
    maxCommitRetryTimeout: -1
    # 二阶段回滚重试超时时长
    maxRollbackRetryTimeout: -1
    # 二阶段提交未完成状态全局事务重试提交线程间隔时间 默认1000，单位毫秒
    recovery:
      committingRetryPeriod: 1000
    # 二阶段异步提交状态重试提交线程间隔时间 默认1000，单位毫秒
      asynCommittingRetryPeriod: 1000
    # 二阶段回滚状态重试回滚线程间隔时间  默认1000，单位毫秒
      rollbackingRetryPeriod: 1000
    # 超时状态检测重试线程间隔时间 默认1000，单位毫秒，检测出超时将全局事务置入回滚会话管理器
      timeoutRetryPeriod: 1000
  vgroupMapping:
    seata-server: default
spring:
  application:
    name: seata-server
logging:
  config: classpath:logback-spring.xml
  file:
    path: /home/logs/seata
  extend:
    logstash-appender:
      destination: 127.0.0.1:4560
    kafka-appender:
      bootstrap-servers: 127.0.0.1:9092
      topic: logback_to_logstash

console:
  user:
    username: seata
    password: ${SEATA_PASSWORD}
seata:
  config:
    type: nacos
    nacos:
      server-addr: nacos:8848
      namespace: ""
      group: DEFAULT_GROUP
      username: nacos
      password: ${NACOS_PASSWORD}
      data-id: seataServer.properties
    #type: file
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: nacos:8848
      group: DEFAULT_GROUP
      namespace: ""
      # tc集群名称
      cluster: default
      username: nacos
      password: ${NACOS_PASSWORD}
#  server:
#    service-port: 8091 #If not configured, the default is '${server.port} + 1000'
  security:
    secretKey: SeataSecretKey0c382ef121d778043159209298fd40bf3850a017
    tokenValidityInMilliseconds: 1800000
    ignore:
      urls: /,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/api/v1/auth/login
store:
  mode: db
  # -----db-----
  db:
    datasource: druid
    dbType: mysql
    # 需要根据mysql的版本调整driverClassName
    # mysql8及以上版本对应的driver：com.mysql.cj.jdbc.Driver
    # mysql8以下版本的driver：com.mysql.jdbc.Driver
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql:3306/seata?useUnicode=true&characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    user: root
    password: ${MYSQL_ROOT_PASSWORD}
    # 数据库初始连接数
    minConn: 1
    # 数据库最大连接数
    maxConn: 20
    # 获取连接时最大等待时间 默认5000，单位毫秒
    maxWait: 5000
    # 全局事务表名 默认global_table
    globalTable: global_table
    # 分支事务表名 默认branch_table
    branchTable: branch_table
    # 全局锁表名 默认lock_table
    lockTable: lock_table
    # 查询全局事务一次的最大条数 默认100
    queryLimit: 100

